# Generated by Django 3.1.5 on 2021-06-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0002_icgroups_parent_guid_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icgroups',
            name='parent_guid_str',
            field=models.CharField(default='str', max_length=36),
        ),
    ]
