# Generated by Django 3.1.5 on 2021-06-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0006_remove_icgroups_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='icgroups',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
