# Generated by Django 3.1.5 on 2021-07-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0007_icgroups_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ic_scu',
            name='ret_price',
        ),
        migrations.RemoveField(
            model_name='ic_scu',
            name='who_price',
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_price', models.PositiveSmallIntegerField(null=True)),
                ('who_price', models.PositiveSmallIntegerField(null=True)),
                ('scu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scu_prices', to='desk_app.ic_scu')),
            ],
        ),
    ]
