# Generated by Django 3.1.5 on 2021-07-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0008_auto_20210703_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='ret_price',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='who_price',
        ),
    ]
