# Generated by Django 3.1.5 on 2021-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0009_auto_20210703_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='ret_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='who_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
