# Generated by Django 3.1.5 on 2021-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0010_auto_20210703_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsDateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('datetime_data', models.DateTimeField()),
            ],
        ),
    ]
