# Generated by Django 3.1.5 on 2021-07-04 17:53

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('desk_app', '0012_icgroups_mptt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ICgroups_mptt',
            new_name='ICgroupsMPTT',
        ),
    ]
