# Generated by Django 3.1.5 on 2021-07-04 17:54

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('desk_app', '0013_auto_20210704_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICgroupsMPTT',
        ),
    ]
