# Generated by Django 3.1.5 on 2021-07-05 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0016_auto_20210704_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icgroups',
            name='parent_guid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='desk_app.icgroups'),
        ),
    ]
