# Generated by Django 3.1.5 on 2021-08-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0017_auto_20210705_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ICgroupsMPTT',
        ),
    ]
