# Generated by Django 3.1.5 on 2021-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0018_delete_icgroupsmptt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ic_scu',
            name='ret_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ic_scu',
            name='who_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
