# Generated by Django 3.1.5 on 2021-08-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0019_auto_20210805_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ret_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('who_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scu_prices', to='desk_app.ic_scu')),
            ],
        ),
    ]
