# Generated by Django 3.1.5 on 2021-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0022_producers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='producers',
            name='barcode_col',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='producers',
            name='file_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producers',
            name='order_col',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
