# Generated by Django 3.1.5 on 2021-09-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk_app', '0023_auto_20210924_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoldersForFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_files', models.CharField(max_length=100)),
                ('ready_files', models.CharField(max_length=100)),
            ],
        ),
    ]
